### ISSUE TITLE
ConsulConfigProcessor uses jsoup without defining the dependency on it

### ISSUE THREAD

**Issue by rsvoboda** [quarkiverse/quarkus-config-extensions#70]
ConsulConfigProcessor uses jsoup without defining the dependency on it

https://github.com/quarkiverse/quarkus-config-extensions/blob/main/consul/deployment/src/main/java/io/quarkus/consul/config/ConsulConfigProcessor.java#L3

Revealed after https://github.com/quarkusio/quarkus/commit/a342c5652677a17a1eaaf209628b4364cdb81251 change when maven-wagon was updated to 3.5.1 and no longer pulls in jsoup dependency
https://mvnrepository.com/artifact/org.apache.maven.wagon/wagon-http-shared/3.4.3
  vs.
https://mvnrepository.com/artifact/org.apache.maven.wagon/wagon-http-shared/3.5.1

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.consul.config.ConsulConfigProcessor#registerForReflection threw an exception: java.lang.NoClassDefFoundError: org/jsoup/Connection$Response
	at io.quarkus.consul.config.ConsulConfigProcessor.registerForReflection(ConsulConfigProcessor.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:944)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ClassNotFoundException: org.jsoup.Connection$Response
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
	... 12 more
```

Noticed in daily runs of https://github.com/quarkus-qe/beefy-scenarios

CC @radcortez / @gsmet

**Comment by radcortez** [comment]
Fixed by https://github.com/quarkiverse/quarkus-config-extensions/pull/72
